// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * <type 'file'> sensor_combined_PubSubMain.cpp
 * This file acts as a main entry point to the application.
 *
 * This file was generated by the tool fastcdrgen.
 */

#include "sensor_combined_Publisher.h"
#include "sensor_combined_Subscriber.h"

#include "UART_node.h"

#include <fastcdr/Cdr.h>
#include <fastcdr/FastCdr.h>
#include <fastcdr/exceptions/Exception.h>
#include <fastrtps/utils/eClock.h>
#include <fastrtps/Domain.h>

#include <unistd.h>

#define BUFFER_SIZE 1024
#define USLEEP_MS 2000

using namespace eprosima;
using namespace eprosima::fastrtps;

int main(int argc, char** argv)
{
    UART_node m_uartNode;
    std::string uart = "/dev/ttyACM0";
    if (argc > 1) uart = std::string(argv[1]);
    if (0 != m_uartNode.init_uart(uart.c_str()))
    {
        printf("EXITING...\n");
        return -1;
    }

    int usleep_ms = USLEEP_MS;
    if (argc > 2) usleep_ms = atoi(argv[2]);

    char data_buffer[BUFFER_SIZE] = {};
    char rx_buffer[BUFFER_SIZE] = {};
    uint32_t rx_buff_pos = 0u;

    // Create subscribers
    sensor_combined_Subscriber sensor_combined_sub;
    if (true == sensor_combined_sub.init()) std::cout << "sensor_combined subscriber created" << std::endl;
    else std::cout << "ERROR creating sensor_combined subscriber" << std::endl;

    // Create publishers
    sensor_combined_Publisher sensor_combined_pub;
    sensor_combined_pub.init();

    int received = 0, sent = 0, wait = 0, total_read = 0;
    int read = 0;
    char topic_ID = 255;

    struct timespec begin;
    bool start = true, receiving = false;
    do
    {
        if (!receiving)
        {
            clock_gettime(0, &begin);
        }
        // Publish messages received from UART
        while (0 < (read = m_uartNode.readFromUART(&topic_ID, data_buffer, rx_buffer, rx_buff_pos, BUFFER_SIZE)))
        {
            switch (topic_ID)
            {
                case 58:
                {
                    sensor_combined_ st;
                    eprosima::fastcdr::FastBuffer cdrbuffer(data_buffer, sizeof(data_buffer));
                    eprosima::fastcdr::Cdr cdr_des(cdrbuffer);
                    st.deserialize(cdr_des);
                    sensor_combined_pub.publish(&st);
                    //printf("                >>[%d] %lu\n", <built-in function id>, st.timestamp());
                    ++received;
                    total_read += read;
                }
                break;
            }
            receiving = true;
            wait = 0;
        }

        // Send subscribed topics over UART
        if (sensor_combined_sub.hasMsg())
        {
            sensor_combined_ msg = sensor_combined_sub.getMsg();
            eprosima::fastcdr::FastBuffer cdrbuffer(data_buffer, sizeof(data_buffer));
            eprosima::fastcdr::Cdr scdr(cdrbuffer);
            msg.serialize(scdr);
            size_t len = scdr.getSerializedDataLength();
            //printf("[%d]>> %lu\n", <built-in function id>, msg.timestamp());
            m_uartNode.writeToUART((char) 58, scdr.getBufferPointer(), len);
            ++sent;
        }

        if (receiving && ++wait > 10)
        {
            struct timespec end;
            clock_gettime(0, &end);
            double elapsed_secs = double(end.tv_sec - begin.tv_sec) + double(end.tv_nsec - begin.tv_nsec)/double(1000000000);
            printf("\nRECEIVED: %d SENT: %d\n%d bytes in %.03f seconds received %.02fKB/s\n",
                    received, sent, total_read, elapsed_secs, (double)total_read/(1000*elapsed_secs));
            received = sent = total_read = wait = 0;
            receiving = false;
        }

        usleep(usleep_ms);
    }while(true);

    return 0;
}
